
-- Nusxa ko'chiring va Supabase SQL Editor'iga joylang (Paste this into Supabase SQL Editor)

-- 1. Fakultetlar jadvali
create table public.faculties (
  id bigint generated by default as identity primary key,
  "nameUz" text not null,
  "nameRu" text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Kafedralar jadvali
create table public.departments (
  id bigint generated by default as identity primary key,
  "facultyId" bigint references public.faculties(id) on delete cascade,
  "nameUz" text not null,
  "nameRu" text not null,
  head text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. O'qituvchilar jadvali
create table public.teachers (
  id bigint generated by default as identity primary key,
  "departmentId" bigint references public.departments(id) on delete cascade,
  name text not null,
  title text,
  specialization text,
  email text,
  phone text,
  experience text,
  bio text,
  image text, -- Base64 yoki rasm URL
  "qrData" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Sharhlar jadvali
create table public.reviews (
  id bigint generated by default as identity primary key,
  "teacherId" bigint references public.teachers(id) on delete cascade,
  "studentName" text,
  anonymous boolean default false,
  rating float,
  scores jsonb, -- { overall: 5, teaching: 4, ... }
  comment text,
  date timestamp with time zone default timezone('utc'::text, now()),
  "isActive" boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) ni o'chirib turamiz (yoki hammaga ruxsat beramiz)
alter table public.faculties enable row level security;
alter table public.departments enable row level security;
alter table public.teachers enable row level security;
alter table public.reviews enable row level security;

-- Hamma uchun o'qish/yozish ruxsati (Test rejimi uchun)
create policy "Public Access Faculties" on public.faculties for all using (true);
create policy "Public Access Departments" on public.departments for all using (true);
create policy "Public Access Teachers" on public.teachers for all using (true);
create policy "Public Access Reviews" on public.reviews for all using (true);

-- Dastlabki ma'lumotlar (MockData dan)
insert into public.faculties ("nameUz", "nameRu") values 
('Filologiya Fakulteti', 'Факультет филологии'),
('Pedagogika Fakulteti', 'Факультет педагогики'),
('Boshlang''ich Ta''lim Fakulteti', 'Факультет начального образования'),
('Aniq va Tabiiy Fanlar Fakulteti', 'Факультет точных и естественных наук'),
('Ijtimoiy va Amaliy Fanlar Fakulteti', 'Факультет социальных и прикладных наук');

-- Kafedralar va O'qituvchilarni qo'lda kiritish yoki Admin paneldan qo'shish mumkin.
